apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-privileged-sa-binding
  namespace: oc-uc1
subjects:
- kind: ServiceAccount
  name: my-privileged-sa
  namespace: oc-uc1
roleRef:
  kind: Role
  name: my-privileged-role
  apiGroup: rbac.authorization.k8s.io
