apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-privileged-sa-binding
subjects:
  - kind: ServiceAccount
    name: my-privileged-sa
    namespace: oc-testenv
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
