# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: haproxy-reload-rolebinding
  namespace: openshift-ingress
subjects:
- kind: ServiceAccount
  name: router
  namespace: openshift-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: haproxy-reload-role